pipeline {
    agent any

    tools {
        maven 'maven3.9.15'
    }

    stages {

        stage('Checkout') {
            steps {
                git branch: 'main',
                    credentialsId: 'github-credentials',
                    url: 'https://github.com/karthi051020/mavendemo.git'
            }
        }

        stage('Build') {
            steps {
                sh 'mvn clean package -DskipTests'
            }
        }

        stage('Test') {
            steps {
                sh 'mvn test'
            }
        }

        stage('Archive') {
            steps {
                archiveArtifacts artifacts: 'target/*.jar'
            }
        }
    }

    post {
        success {
            mail to: 'kkarthi1605email.com',
                 subject: "✅ SUCCESS: ${env.JOB_NAME} #${env.BUILD_NUMBER}",
                 body: "Build passed. URL: ${env.BUILD_URL}"
        }
        failure {
            mail to: 'kkarthi1605@email.com',
                 subject: "❌ FAILED: ${env.JOB_NAME} #${env.BUILD_NUMBER}",
                 body: "Build failed. URL: ${env.BUILD_URL}"
        }
        always {
            cleanWs()
        }
    }
}
